version: '3'
services:
    nginx:
        image: nginx:1.21.0-alpine
        container_name: nginx
        hostname: nginx
        ports:
            - "5480:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/public:/usr/share/nginx/html/public:ro

    postgres:
        image: postgres:12.7-alpine
        container_name: postgres
        hostname: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            LANG: ja_JP.utf8
        volumes: 
            - ./postgres/entrypoint:/docker-entrypoint-initdb.d
            # - ./postgres/data:/var/lib/postgresql/data 
        ports:
            - '5432:5432'

    pgweb:
        container_name: pgweb
        hostname: pgweb
        image: sosedoff/pgweb
        restart: always
        ports:
            - '5433:8081'
        environment:
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
        depends_on:
            - postgres
